#!/bin/bash
set -euo pipefail

# ==================================================================
# ROOT
# ==================================================================

cd ~
mkdir -p repos

# ==================================================================
# PACKAGES
# ==================================================================

echo "Installing Homebrew"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo "Adding Homebrew taps"
homebrew_taps=(
	"caskroom/cask"
  "caskroom/fonts"
)
for homebrew_tap in "${homebrew_taps[@]}"; do
	brew tap "$homebrew_tap"
done

echo "Installing global Homebrew packages"

homebrew_packages=(
  "git"
  "mas"
  "yarn"
  "nvm"
  "tig"
  "zsh" 
  "zsh-completions"
)

for homebrew_package in "${homebrew_packages[@]}"; do
  brew install "$homebrew_package"
done

echo "Installing Node"
. ~/.nvm/nvm.sh
nvm install --lts
nvm use --lts

echo "Upgrading npm"
npm install -g npm

echo "Installing npm packages"

npm_packages=(
  "create-react-app"
)

for npm_package in "${npm_packages[@]}"; do
  npm install -g "$npm_package"
done


# ==================================================================
# APPS 
# ==================================================================

echo "Installing Homebrew cask apps and fonts"

homebrew_cask_packages=(
  "arq"
  "cold-turkey-blocker"
  "docker"
  "font-fira-code"
  "font-meslo-for-powerline"
  "google-chrome"
  "gpg-suite"
  "iterm2"
  "postman"
  "scroll-reverser"
  "slack"
  "spotify"
  "virtualbox"
  "visual-studio-code"
  "vlc"
  "whatsapp"
  "notion"

)

for homebrew_cask_package in "${homebrew_cask_packages[@]}"; do
  brew cask install "$homebrew_cask_package"
done

echo "Installing Mac App Store apps"

mac_app_store_apps=(
  "585829637" # Todoist
  "836505650" # Battery Monitor
  "931134707" # Wire
  "568494494" # Pocket
  "732710998" # Enpass
)
for mac_app_store_app in "${mac_app_store_apps[@]}"; do
  mas install "$mac_app_store_app"
done

# ==================================================================
# VS Code
# ==================================================================

echo "Setting up VS Code"

cat << EOF >> ~/.bash_profile
# Add Visual Studio Code (code)
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
EOF

vscode_extensions=("Compulim.vscode-clock"
"amatiasq.sort-imports"
"capaj.vscode-exports-autocomplete"
"christian-kohler.path-intellisense"
"dbaeumer.vscode-eslint"
"eamodio.gitlens"
"EditorConfig.EditorConfig"
"eg2.tslint"
"esbenp.prettier-vscode"
"kumar-harsh.graphql-for-vscode"
"ms-vsliveshare.vsliveshare"
"naumovs.color-highlight"
"octref.vetur"
"robertohuertasm.vscode-icons")

for vscode_extension in "${vscode_extensions[@]}"; do
  code --install-extension "$vscode_extension"
done


# ==================================================================
# REPOS
# ==================================================================

cd ~/repos

echo "Cloning scripts"
git clone git@github.com:fhavrlent/scripts.git

echo "Cloning dotfiles"
git clone git@github.com:fhavrlent/dotfiles.git


# ==================================================================
# DOTFILES
# ==================================================================

cd ~/repos/dotfiles

echo "VS Code dotfiles"
rm -f ~/Library/Application\ Support/Code/User/settings.json
ln ./vscode.json ~/Library/Application\ Support/Code/User/settings.json



# ==================================================================
# MACOS
# ==================================================================

# SCREENSHOTS

echo "Configuring screenshots to save in Downloads"
defaults write com.apple.screencapture location ~/Downloads
killall SystemUIServer


# DS_STORE

echo "Turning off .DS_Store on network drives"
defaults write com.apple.desktopservices DSDontWriteNetworkStores true

# ==================================================================
# oh-my-zsh
# ==================================================================

echo "Setting up oh-my-zsh"
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
echo "zsh dotfiles"
rm -f ~/.zshrc
ln .zshrc ~/.zshrc
source ~/.zshrc

cd ~
